environment:
  AV_PROJECTS: 'c:\projects'
  AV_BF_M2: 'c:\projects\m2'
  AV_BF_SOURCE: 'c:\projects\bioformats-examples'

# Note that only Oracle JDK is provided.
  matrix:
    - java: 9
      build: "gradle publishToMavenLocal"
    - java: 9
      build: "mvn install"
    - java: 1.8
      build: "gradle publishToMavenLocal"
    - java: 1.8
      build: mvn install
    - java: 1.7
      build: "gradle publishToMavenLocal"
    - java: 1.7
      build: "mvn install"

cache:
  - '%AV_BF_M2% -> appveyor.yml'

os: 'Visual Studio 2015'
clone_folder: '%AV_BF_SOURCE%'
clone_depth: 5
platform: x64

init:
  - git config --global core.autocrlf input
  - 'mkdir %HOMEDRIVE%\%HOMEPATH%\.gradle'
  - 'echo org.gradle.daemon=false > %HOMEDRIVE%\%HOMEPATH%\.gradle\gradle.properties'
  - 'if "%build%" == "gradle publishToMavenLocal" choco install gradle'
  - refreshenv
  - 'if [%java%] == [1.7] set "JAVA_HOME=C:\Program Files\Java\jdk1.7.0"'
  - 'if [%java%] == [1.8] set "JAVA_HOME=C:\Program Files\Java\jdk1.8.0"'
  - 'if [%java%] == [9] set "JAVA_HOME=C:\Program Files\Java\jdk9"'
  - PATH=%JAVA_HOME%\bin;%PATH%
  - 'set "MAVEN_OPTS=-Dmaven.repo.local=%AV_BF_M2%"'

build_script:
  - '%build%'
